#+TITLE: guix-forge

/guix-forge/ is a Guix service that lets you run a complete [[https://en.wikipedia.org/wiki/Forge_(software)][software forge]] in the manner of GitHub, GitLab, etc. Unlike other free software forges such as GitLab, Gitea, etc., /guix-forge/ is not a monolith but is an assemblage of several pieces of server software wired up to function as one. In this sense, it is a /meta-service/. /guix-forge/ does for software forges what [[https://mailinabox.email/][Mail-in-a-Box]] does for email.

/guix-forge/ is provided on a best effort basis. Its design is unstable, and open to change. We will try our best to not break your system configuration often, but it might happen.

* Installation

/guix-forge/ is distributed as a Guix channel. To use it, add the following channel definition to your ~/.config/guix/channels.scm file.

#+BEGIN_SRC scheme
  (channel
   (name 'guix-forge)
   (url "https://git.systemreboot.net/guix-forge/")
   (branch "main")
   (introduction
    (make-channel-introduction
     "0432e37b20dd678a02efee21adf0b9525a670310"
     (openpgp-fingerprint
      "7F73 0343 F2F0 9F3C 77BF  79D3 2E25 EE8B 6180 2BB3"))))
#+END_SRC

* Philosophy

In order to empower ordinary users, software should not just be free (as in freedom), but also be simple and easy to deploy, especially for small-scale deployments. /guix-forge/ is therefore minimalistic, and does not require running large database servers such as MariaDB and PostgreSQL.

While some state is inevitable, server software should strive to be as stateless as an old analog television set. You switch it on, and it works all the time. There are no pesky software updates, and complex hidden state. /guix-forge/ tries to be as stateless as possible. Almost all of /guix-forge's/ state can be version controlled, and the rest are simple files that can be backed up easily.

[[https://drewdevault.com/2018/07/23/Git-is-already-distributed.html][Git is already federated and decentralized]] with email. /guix-forge/ acknowledges this and prefers to support git's [[https://drewdevault.com/2018/07/02/Email-driven-git.html][email driven workflow]] with project discussion, bug reports and patches all happening over email.
